import { defineField, defineType } from "sanity";

export default defineType({
  name: "order",
  title: "Order",
  type: "document",
  fields: [
    defineField({
      name: "items",
      title: "Order items",
      type: "array",
      description: "These are autogenerated. Best not to touch them",
      of: [
        {
          type: "document",
          fields: [
            defineField({
              name: "itemName",
              title: "Item name",
              type: "string",
            }),
            defineField({
              name: "price",
              title: "Price",
              type: "number",
            }),
            defineField({
              name: "quantity",
              title: "Quantity",
              type: "number",
            }),
            defineField({
              name: "prescription",
              title: "Prescription",
              type: "string",
            }),
          ],
        },
      ],
    }),
    defineField({
      name: "total",
      title: "Total",
      type: "number",
    }),

    defineField({
      name: "shipping",
      title: "Shipping",
      type: "number",
    }),
    defineField({
      name: "customer",
      title: "Name of customer",
      type: "string",
    }),
    defineField({
      name: "email",
      title: "Email",
      type: "string",
    }),
    defineField({
      name: "address",
      title: "Address",
      type: "string",
    }),
    defineField({
      name: "region",
      title: "Region",
      type: "string",
    }),
    defineField({
      name: "city",
      title: "City/Town",
      type: "string",
    }),
    defineField({
      name: "phone",
      title: "Phone",
      type: "string",
    }),
  ],
});
